-- ==================== PAYSTACK SUBSCRIPTION TABLES ====================
-- This migration creates the necessary tables for Paystack subscription management
-- Single ZAR 200/month subscription model for user access to trading profiles
--
-- Run with: psql -U postgres -d trading_platform -f database/create_subscription_tables.sql

-- ==================== Step 1: Modify users table ====================
-- Add subscription fields to existing users table

ALTER TABLE users
ADD COLUMN IF NOT EXISTS subscription_status VARCHAR(20) DEFAULT 'inactive' CHECK (subscription_status IN ('active', 'inactive', 'cancelled', 'expired'));

ALTER TABLE users
ADD COLUMN IF NOT EXISTS subscription_code VARCHAR(255) UNIQUE;

ALTER TABLE users
ADD COLUMN IF NOT EXISTS subscription_started_at TIMESTAMP;

ALTER TABLE users
ADD COLUMN IF NOT EXISTS subscription_expires_at TIMESTAMP;

ALTER TABLE users
ADD COLUMN IF NOT EXISTS auto_renew BOOLEAN DEFAULT TRUE;

-- Add indexes for subscription queries
CREATE INDEX IF NOT EXISTS idx_users_subscription_status
ON users(subscription_status);

CREATE INDEX IF NOT EXISTS idx_users_subscription_expires
ON users(subscription_expires_at)
WHERE subscription_status = 'active';

-- Add comments
COMMENT ON COLUMN users.subscription_status IS 'Current subscription status: active, inactive, cancelled, expired';
COMMENT ON COLUMN users.subscription_code IS 'Paystack subscription code for recurring billing';
COMMENT ON COLUMN users.subscription_started_at IS 'When the subscription started';
COMMENT ON COLUMN users.subscription_expires_at IS 'When the current billing period expires';
COMMENT ON COLUMN users.auto_renew IS 'Whether subscription auto-renews at expiration';

-- ==================== Step 2: Create payment_history table ====================
-- Tracks all payment transactions via Paystack

CREATE TABLE IF NOT EXISTS payment_history (
    id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,

    -- Paystack transaction details
    reference VARCHAR(255) UNIQUE NOT NULL,
    paystack_reference VARCHAR(255),
    authorization_code VARCHAR(255),

    -- Payment details
    amount DECIMAL(10, 2) NOT NULL,
    currency VARCHAR(3) DEFAULT 'USD',
    channel VARCHAR(50),  -- card, bank, ussd, qr, mobile_money

    -- Status tracking
    status VARCHAR(20) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'success', 'failed', 'abandoned')),
    payment_type VARCHAR(20) DEFAULT 'subscription' CHECK (payment_type IN ('subscription', 'renewal', 'manual')),

    -- Metadata
    customer_email VARCHAR(255),
    ip_address VARCHAR(45),
    metadata JSONB,  -- Store additional Paystack metadata

    -- Timestamps
    paid_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    -- Indexes
    CONSTRAINT fk_payment_user FOREIGN KEY (user_id) REFERENCES users(id)
);

-- Indexes for payment_history
CREATE INDEX IF NOT EXISTS idx_payment_user_id ON payment_history(user_id);
CREATE INDEX IF NOT EXISTS idx_payment_reference ON payment_history(reference);
CREATE INDEX IF NOT EXISTS idx_payment_status ON payment_history(status);
CREATE INDEX IF NOT EXISTS idx_payment_created_at ON payment_history(created_at DESC);

-- Comments
COMMENT ON TABLE payment_history IS 'Tracks all Paystack payment transactions';
COMMENT ON COLUMN payment_history.reference IS 'Unique transaction reference (generated by us)';
COMMENT ON COLUMN payment_history.paystack_reference IS 'Paystack transaction reference';
COMMENT ON COLUMN payment_history.authorization_code IS 'Paystack authorization code for recurring charges';
COMMENT ON COLUMN payment_history.metadata IS 'Additional Paystack webhook data in JSON format';

-- ==================== Step 3: Create webhook_logs table ====================
-- Logs all incoming Paystack webhooks for debugging and audit

CREATE TABLE IF NOT EXISTS webhook_logs (
    id SERIAL PRIMARY KEY,

    -- Webhook details
    event_type VARCHAR(100) NOT NULL,  -- charge.success, subscription.create, etc.
    reference VARCHAR(255),

    -- Request data
    payload JSONB NOT NULL,  -- Full webhook payload
    signature VARCHAR(255),  -- Paystack signature for verification
    ip_address VARCHAR(45),

    -- Processing status
    processed BOOLEAN DEFAULT FALSE,
    processing_error TEXT,

    -- Timestamps
    received_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    processed_at TIMESTAMP,

    -- Metadata
    user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
    payment_id INTEGER REFERENCES payment_history(id) ON DELETE SET NULL
);

-- Indexes for webhook_logs
CREATE INDEX IF NOT EXISTS idx_webhook_event_type ON webhook_logs(event_type);
CREATE INDEX IF NOT EXISTS idx_webhook_reference ON webhook_logs(reference);
CREATE INDEX IF NOT EXISTS idx_webhook_processed ON webhook_logs(processed);
CREATE INDEX IF NOT EXISTS idx_webhook_received_at ON webhook_logs(received_at DESC);

-- Comments
COMMENT ON TABLE webhook_logs IS 'Logs all Paystack webhook events for debugging and audit trail';
COMMENT ON COLUMN webhook_logs.event_type IS 'Paystack event type (e.g., charge.success, subscription.disable)';
COMMENT ON COLUMN webhook_logs.payload IS 'Full JSON payload from Paystack webhook';
COMMENT ON COLUMN webhook_logs.signature IS 'Paystack webhook signature for security verification';
COMMENT ON COLUMN webhook_logs.processed IS 'Whether this webhook has been successfully processed';

-- ==================== Step 4: Create subscription plans table ====================
-- Stores subscription plan configuration (single ZAR 200 plan for now, but extensible)

CREATE TABLE IF NOT EXISTS subscription_plans (
    id SERIAL PRIMARY KEY,

    -- Plan details
    name VARCHAR(100) NOT NULL,
    description TEXT,
    plan_code VARCHAR(100) UNIQUE NOT NULL,  -- Paystack plan code

    -- Pricing
    amount DECIMAL(10, 2) NOT NULL,
    currency VARCHAR(3) DEFAULT 'USD',
    interval VARCHAR(20) DEFAULT 'monthly' CHECK (interval IN ('monthly', 'annually')),

    -- Status
    is_active BOOLEAN DEFAULT TRUE,

    -- Timestamps
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Insert default ZAR 200/month plan (Paystack-generated plan code)
INSERT INTO subscription_plans (name, description, plan_code, amount, currency, interval, is_active)
VALUES (
    'Trading Dashboard Monthly',
    'Access to all trading profiles, indicators, and models',
    'PLN_o6aocIukczuw4dk',
    200.00,
    'ZAR',
    'monthly',
    TRUE
)
ON CONFLICT (plan_code) DO NOTHING;

-- Comments
COMMENT ON TABLE subscription_plans IS 'Subscription plan configurations';
COMMENT ON COLUMN subscription_plans.plan_code IS 'Unique Paystack plan code';

-- ==================== Step 5: Add trigger for updated_at ====================
-- Auto-update updated_at timestamp

CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Apply to payment_history
DROP TRIGGER IF EXISTS update_payment_history_updated_at ON payment_history;
CREATE TRIGGER update_payment_history_updated_at
    BEFORE UPDATE ON payment_history
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- Apply to subscription_plans
DROP TRIGGER IF EXISTS update_subscription_plans_updated_at ON subscription_plans;
CREATE TRIGGER update_subscription_plans_updated_at
    BEFORE UPDATE ON subscription_plans
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- ==================== Success Message ====================
DO $$
BEGIN
    RAISE NOTICE '✓ Subscription tables created successfully';
    RAISE NOTICE '✓ Default ZAR 200/month plan inserted';
    RAISE NOTICE '';
    RAISE NOTICE 'Next steps:';
    RAISE NOTICE '1. Configure Paystack API keys in .env';
    RAISE NOTICE '2. Plan already created in Paystack dashboard: PLN_o6aocIukczuw4dk';
    RAISE NOTICE '3. Configure webhook URL in Paystack dashboard';
    RAISE NOTICE '4. Test subscription flow';
END $$;
